cask_args appdir: '/Applications'

tap 'homebrew/bundle'
tap 'puma/puma'

brew 'ack'
brew 'coreutils'
brew 'elasticsearch'
brew 'go'
brew 'grc'
brew 'imagemagick'
brew 'jp2a'
brew 'jq'
brew 'libcaca', args: ['with-imlib2']
brew 'libgit2'
brew 'openssl'
brew 'node'
brew 'readline'
brew 'postgresql'
brew 'rbenv'
brew 'redis'
brew 'roundup'
brew 'spaceman-diff'
brew 'spark'
brew 'unrar'
brew 'wget'
brew 'yarn'
brew 'youtube-dl'

cask 'boxer'
cask 'firefox'
cask 'google-chrome'
cask 'handbrake'
cask 'seashore'
cask 'slack'
cask 'steam'
cask 'transmission'
cask 'tunnelbear'
casl 'visual-studio-code'
cask 'vlc'
